name: Build, Push php 8.1 image

on:
  push:
    branches: [ master ]
    paths:
      - docker/php/Dockerfile81

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build
      run: docker build . --file docker/php/Dockerfile81 --tag ammardev0/php:8.1 --tag ammardev0/php:latest

    - name: Push
      run: docker push ammardev0/php:8.1

    - name: Push latest tag
      run: docker push ammardev0/php:latest