name: Build, Push php 8.0 image

on:
  push:
    branches: [ master ]
    paths:
      - Dockerfiles/Dockerfile80

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build
      run: docker build . --file Dockerfiles/Dockerfile80 --tag ammardev0/php:8.0

    - name: Push
      run: docker push ammardev0/php:8.0